FROM nginx:1.14.1-alpine

## Copy our default nginx config
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

## Remove default nginx website
RUN rm -rf /usr/share/nginx/admin/*
RUN mkdir /usr/share/nginx/admin

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY docker/index.html /usr/share/nginx/html
COPY angular/dist/admin /usr/share/nginx/admin/admin

CMD ["nginx", "-g", "daemon off;"]