### STAGE 1: Build ###

# We label our stage as ‘builder’
FROM snellocms/snello-admin-builder:latest as builder

ADD angular/src  ./src
ADD angular/e2e  ./e2e
ADD angular/*.json ./

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
WORKDIR .

RUN npm i && $(npm bin)/ng build --prod --base-href=/admin --deploy-url=/admin/
### STAGE 2: Setup ###

FROM nginx:1.14.1-alpine

## Copy our default nginx config
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

## Remove default nginx website
RUN rm -rf /usr/share/nginx/admin/*
RUN mkdir /usr/share/nginx/admin

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder /ng-app/dist/admin /usr/share/nginx/admin/admin
COPY docker/index.html /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]