package io.snello;

import org.junit.Test;

import java.util.Arrays;

public class SelectItemsGenera {
    @Test
    public void genera() {
        String eccole = "fa-glass\n" +
                "fa-music\n" +
                "fa-search\n" +
                "fa-envelope-o\n" +
                "fa-heart\n" +
                "fa-star\n" +
                "fa-star-o\n" +
                "fa-user\n" +
                "fa-film\n" +
                "fa-th-large\n" +
                "fa-th\n" +
                "fa-th-list\n" +
                "fa-check\n" +
                "fa-times\n" +
                "fa-search-plus\n" +
                "fa-search-minus\n" +
                "fa-power-off\n" +
                "fa-signal\n" +
                "fa-cog\n" +
                "fa-trash-o\n" +
                "fa-home\n" +
                "fa-file-o\n" +
                "fa-clock-o\n" +
                "fa-road\n" +
                "fa-download\n" +
                "fa-arrow-circle-o-down\n" +
                "fa-arrow-circle-o-up\n" +
                "fa-inbox\n" +
                "fa-play-circle-o\n" +
                "fa-repeat\n" +
                "fa-refresh\n" +
                "fa-list-alt\n" +
                "fa-lock\n" +
                "fa-flag\n" +
                "fa-headphones\n" +
                "fa-volume-off\n" +
                "fa-volume-down\n" +
                "fa-volume-up\n" +
                "fa-qrcode\n" +
                "fa-barcode\n" +
                "fa-tag\n" +
                "fa-tags\n" +
                "fa-book\n" +
                "fa-bookmark\n" +
                "fa-print\n" +
                "fa-camera\n" +
                "fa-font\n" +
                "fa-bold\n" +
                "fa-italic\n" +
                "fa-text-height\n" +
                "fa-text-width\n" +
                "fa-align-left\n" +
                "fa-align-center\n" +
                "fa-align-right\n" +
                "fa-align-justify\n" +
                "fa-list\n" +
                "fa-outdent\n" +
                "fa-indent\n" +
                "fa-video-camera\n" +
                "fa-picture-o\n" +
                "fa-pencil\n" +
                "fa-map-marker\n" +
                "fa-adjust\n" +
                "fa-tint\n" +
                "fa-pencil-square-o\n" +
                "fa-share-square-o\n" +
                "fa-check-square-o\n" +
                "fa-arrows\n" +
                "fa-step-backward\n" +
                "fa-fast-backward\n" +
                "fa-backward\n" +
                "fa-play\n" +
                "fa-pause\n" +
                "fa-stop\n" +
                "fa-forward\n" +
                "fa-fast-forward\n" +
                "fa-step-forward\n" +
                "fa-eject\n" +
                "fa-chevron-left\n" +
                "fa-chevron-right\n" +
                "fa-plus-circle\n" +
                "fa-minus-circle\n" +
                "fa-times-circle\n" +
                "fa-check-circle\n" +
                "fa-question-circle\n" +
                "fa-info-circle\n" +
                "fa-crosshairs\n" +
                "fa-times-circle-o\n" +
                "fa-check-circle-o\n" +
                "fa-ban\n" +
                "fa-arrow-left\n" +
                "fa-arrow-right\n" +
                "fa-arrow-up\n" +
                "fa-arrow-down\n" +
                "fa-share\n" +
                "fa-expand\n" +
                "fa-compress\n" +
                "fa-plus\n" +
                "fa-minus\n" +
                "fa-asterisk\n" +
                "fa-exclamation-circle\n" +
                "fa-gift\n" +
                "fa-leaf\n" +
                "fa-fire\n" +
                "fa-eye\n" +
                "fa-eye-slash\n" +
                "fa-exclamation-triangle\n" +
                "fa-plane\n" +
                "fa-calendar\n" +
                "fa-random\n" +
                "fa-comment\n" +
                "fa-magnet\n" +
                "fa-chevron-up\n" +
                "fa-chevron-down\n" +
                "fa-retweet\n" +
                "fa-shopping-cart\n" +
                "fa-folder\n" +
                "fa-folder-open\n" +
                "fa-arrows-v\n" +
                "fa-arrows-h\n" +
                "fa-bar-chart\n" +
                "fa-twitter-square\n" +
                "fa-facebook-square\n" +
                "fa-camera-retro\n" +
                "fa-key\n" +
                "fa-cogs\n" +
                "fa-comments\n" +
                "fa-thumbs-o-up\n" +
                "fa-thumbs-o-down\n" +
                "fa-star-half\n" +
                "fa-heart-o\n" +
                "fa-sign-out\n" +
                "fa-linkedin-square\n" +
                "fa-thumb-tack\n" +
                "fa-external-link\n" +
                "fa-sign-in\n" +
                "fa-trophy\n" +
                "fa-github-square\n" +
                "fa-upload\n" +
                "fa-lemon-o\n" +
                "fa-phone\n" +
                "fa-square-o\n" +
                "fa-bookmark-o\n" +
                "fa-phone-square\n" +
                "fa-twitter\n" +
                "fa-facebook\n" +
                "fa-github\n" +
                "fa-unlock\n" +
                "fa-credit-card\n" +
                "fa-rss\n" +
                "fa-hdd-o\n" +
                "fa-bullhorn\n" +
                "fa-bell\n" +
                "fa-certificate\n" +
                "fa-hand-o-right\n" +
                "fa-hand-o-left\n" +
                "fa-hand-o-up\n" +
                "fa-hand-o-down\n" +
                "fa-arrow-circle-left\n" +
                "fa-arrow-circle-right\n" +
                "fa-arrow-circle-up\n" +
                "fa-arrow-circle-down\n" +
                "fa-globe\n" +
                "fa-wrench\n" +
                "fa-tasks\n" +
                "fa-filter\n" +
                "fa-briefcase\n" +
                "fa-arrows-alt\n" +
                "fa-users\n" +
                "fa-link\n" +
                "fa-cloud\n" +
                "fa-flask\n" +
                "fa-scissors\n" +
                "fa-files-o\n" +
                "fa-paperclip\n" +
                "fa-floppy-o\n" +
                "fa-square\n" +
                "fa-bars\n" +
                "fa-list-ul\n" +
                "fa-list-ol\n" +
                "fa-strikethrough\n" +
                "fa-underline\n" +
                "fa-table\n" +
                "fa-magic\n" +
                "fa-truck\n" +
                "fa-pinterest\n" +
                "fa-pinterest-square\n" +
                "fa-google-plus-square\n" +
                "fa-google-plus\n" +
                "fa-money\n" +
                "fa-caret-down\n" +
                "fa-caret-up\n" +
                "fa-caret-left\n" +
                "fa-caret-right\n" +
                "fa-columns\n" +
                "fa-sort\n" +
                "fa-sort-desc\n" +
                "fa-sort-asc\n" +
                "fa-envelope\n" +
                "fa-linkedin\n" +
                "fa-undo\n" +
                "fa-gavel\n" +
                "fa-tachometer\n" +
                "fa-comment-o\n" +
                "fa-comments-o\n" +
                "fa-bolt\n" +
                "fa-sitemap\n" +
                "fa-umbrella\n" +
                "fa-clipboard\n" +
                "fa-lightbulb-o\n" +
                "fa-exchange\n" +
                "fa-cloud-download\n" +
                "fa-cloud-upload\n" +
                "fa-user-md\n" +
                "fa-stethoscope\n" +
                "fa-suitcase\n" +
                "fa-bell-o\n" +
                "fa-coffee\n" +
                "fa-cutlery\n" +
                "fa-file-text-o\n" +
                "fa-building-o\n" +
                "fa-hospital-o\n" +
                "fa-ambulance\n" +
                "fa-medkit\n" +
                "fa-fighter-jet\n" +
                "fa-beer\n" +
                "fa-h-square\n" +
                "fa-plus-square\n" +
                "fa-angle-double-left\n" +
                "fa-angle-double-right\n" +
                "fa-angle-double-up\n" +
                "fa-angle-double-down\n" +
                "fa-angle-left\n" +
                "fa-angle-right\n" +
                "fa-angle-up\n" +
                "fa-angle-down\n" +
                "fa-desktop\n" +
                "fa-laptop\n" +
                "fa-tablet\n" +
                "fa-mobile\n" +
                "fa-circle-o\n" +
                "fa-quote-left\n" +
                "fa-quote-right\n" +
                "fa-spinner\n" +
                "fa-circle\n" +
                "fa-reply\n" +
                "fa-github-alt\n" +
                "fa-folder-o\n" +
                "fa-folder-open-o\n" +
                "fa-smile-o\n" +
                "fa-frown-o\n" +
                "fa-meh-o\n" +
                "fa-gamepad\n" +
                "fa-keyboard-o\n" +
                "fa-flag-o\n" +
                "fa-flag-checkered\n" +
                "fa-terminal\n" +
                "fa-code\n" +
                "fa-reply-all\n" +
                "fa-star-half-o\n" +
                "fa-location-arrow\n" +
                "fa-crop\n" +
                "fa-code-fork\n" +
                "fa-chain-broken\n" +
                "fa-question\n" +
                "fa-info\n" +
                "fa-exclamation\n" +
                "fa-superscript\n" +
                "fa-subscript\n" +
                "fa-eraser\n" +
                "fa-puzzle-piece\n" +
                "fa-microphone\n" +
                "fa-microphone-slash\n" +
                "fa-shield\n" +
                "fa-calendar-o\n" +
                "fa-fire-extinguisher\n" +
                "fa-rocket\n" +
                "fa-maxcdn\n" +
                "fa-chevron-circle-left\n" +
                "fa-chevron-circle-right\n" +
                "fa-chevron-circle-up\n" +
                "fa-chevron-circle-down\n" +
                "fa-html5\n" +
                "fa-css3\n" +
                "fa-anchor\n" +
                "fa-unlock-alt\n" +
                "fa-bullseye\n" +
                "fa-ellipsis-h\n" +
                "fa-ellipsis-v\n" +
                "fa-rss-square\n" +
                "fa-play-circle\n" +
                "fa-ticket\n" +
                "fa-minus-square\n" +
                "fa-minus-square-o\n" +
                "fa-level-up\n" +
                "fa-level-down\n" +
                "fa-check-square\n" +
                "fa-pencil-square\n" +
                "fa-external-link-square\n" +
                "fa-share-square\n" +
                "fa-compass\n" +
                "fa-caret-square-o-down\n" +
                "fa-caret-square-o-up\n" +
                "fa-caret-square-o-right\n" +
                "fa-eur\n" +
                "fa-gbp\n" +
                "fa-usd\n" +
                "fa-inr\n" +
                "fa-jpy\n" +
                "fa-rub\n" +
                "fa-krw\n" +
                "fa-btc\n" +
                "fa-file\n" +
                "fa-file-text\n" +
                "fa-sort-alpha-asc\n" +
                "fa-sort-alpha-desc\n" +
                "fa-sort-amount-asc\n" +
                "fa-sort-amount-desc\n" +
                "fa-sort-numeric-asc\n" +
                "fa-sort-numeric-desc\n" +
                "fa-thumbs-up\n" +
                "fa-thumbs-down\n" +
                "fa-youtube-square\n" +
                "fa-youtube\n" +
                "fa-xing\n" +
                "fa-xing-square\n" +
                "fa-youtube-play\n" +
                "fa-dropbox\n" +
                "fa-stack-overflow\n" +
                "fa-instagram\n" +
                "fa-flickr\n" +
                "fa-adn\n" +
                "fa-bitbucket\n" +
                "fa-bitbucket-square\n" +
                "fa-tumblr\n" +
                "fa-tumblr-square\n" +
                "fa-long-arrow-down\n" +
                "fa-long-arrow-up\n" +
                "fa-long-arrow-left\n" +
                "fa-long-arrow-right\n" +
                "fa-apple\n" +
                "fa-windows\n" +
                "fa-android\n" +
                "fa-linux\n" +
                "fa-dribbble\n" +
                "fa-skype\n" +
                "fa-foursquare\n" +
                "fa-trello\n" +
                "fa-female\n" +
                "fa-male\n" +
                "fa-gratipay\n" +
                "fa-sun-o\n" +
                "fa-moon-o\n" +
                "fa-archive\n" +
                "fa-bug\n" +
                "fa-vk\n" +
                "fa-weibo\n" +
                "fa-renren\n" +
                "fa-pagelines\n" +
                "fa-stack-exchange\n" +
                "fa-arrow-circle-o-right\n" +
                "fa-arrow-circle-o-left\n" +
                "fa-caret-square-o-left\n" +
                "fa-dot-circle-o\n" +
                "fa-wheelchair\n" +
                "fa-vimeo-square\n" +
                "fa-try\n" +
                "fa-plus-square-o\n" +
                "fa-space-shuttle\n" +
                "fa-slack\n" +
                "fa-envelope-square\n" +
                "fa-wordpress\n" +
                "fa-openid\n" +
                "fa-university\n" +
                "fa-graduation-cap\n" +
                "fa-yahoo\n" +
                "fa-google\n" +
                "fa-reddit\n" +
                "fa-reddit-square\n" +
                "fa-stumbleupon-circle\n" +
                "fa-stumbleupon\n" +
                "fa-delicious\n" +
                "fa-digg\n" +
                "fa-pied-piper-pp\n" +
                "fa-pied-piper-alt\n" +
                "fa-drupal\n" +
                "fa-joomla\n" +
                "fa-language\n" +
                "fa-fax\n" +
                "fa-building\n" +
                "fa-child\n" +
                "fa-paw\n" +
                "fa-spoon\n" +
                "fa-cube\n" +
                "fa-cubes\n" +
                "fa-behance\n" +
                "fa-behance-square\n" +
                "fa-steam\n" +
                "fa-steam-square\n" +
                "fa-recycle\n" +
                "fa-car\n" +
                "fa-taxi\n" +
                "fa-tree\n" +
                "fa-spotify\n" +
                "fa-deviantart\n" +
                "fa-soundcloud\n" +
                "fa-database\n" +
                "fa-file-pdf-o\n" +
                "fa-file-word-o\n" +
                "fa-file-excel-o\n" +
                "fa-file-powerpoint-o\n" +
                "fa-file-image-o\n" +
                "fa-file-archive-o\n" +
                "fa-file-audio-o\n" +
                "fa-file-video-o\n" +
                "fa-file-code-o\n" +
                "fa-vine\n" +
                "fa-codepen\n" +
                "fa-jsfiddle\n" +
                "fa-life-ring\n" +
                "fa-circle-o-notch\n" +
                "fa-rebel\n" +
                "fa-empire\n" +
                "fa-git-square\n" +
                "fa-git\n" +
                "fa-hacker-news\n" +
                "fa-tencent-weibo\n" +
                "fa-qq\n" +
                "fa-weixin\n" +
                "fa-paper-plane\n" +
                "fa-paper-plane-o\n" +
                "fa-history\n" +
                "fa-circle-thin\n" +
                "fa-header\n" +
                "fa-paragraph\n" +
                "fa-sliders\n" +
                "fa-share-alt\n" +
                "fa-share-alt-square\n" +
                "fa-bomb\n" +
                "fa-futbol-o\n" +
                "fa-tty\n" +
                "fa-binoculars\n" +
                "fa-plug\n" +
                "fa-slideshare\n" +
                "fa-twitch\n" +
                "fa-yelp\n" +
                "fa-newspaper-o\n" +
                "fa-wifi\n" +
                "fa-calculator\n" +
                "fa-paypal\n" +
                "fa-google-wallet\n" +
                "fa-cc-visa\n" +
                "fa-cc-mastercard\n" +
                "fa-cc-discover\n" +
                "fa-cc-amex\n" +
                "fa-cc-paypal\n" +
                "fa-cc-stripe\n" +
                "fa-bell-slash\n" +
                "fa-bell-slash-o\n" +
                "fa-trash\n" +
                "fa-copyright\n" +
                "fa-at\n" +
                "fa-eyedropper\n" +
                "fa-paint-brush\n" +
                "fa-birthday-cake\n" +
                "fa-area-chart\n" +
                "fa-pie-chart\n" +
                "fa-line-chart\n" +
                "fa-lastfm\n" +
                "fa-lastfm-square\n" +
                "fa-toggle-off\n" +
                "fa-toggle-on\n" +
                "fa-bicycle\n" +
                "fa-bus\n" +
                "fa-ioxhost\n" +
                "fa-angellist\n" +
                "fa-cc\n" +
                "fa-ils\n" +
                "fa-meanpath\n" +
                "fa-buysellads\n" +
                "fa-connectdevelop\n" +
                "fa-dashcube\n" +
                "fa-forumbee\n" +
                "fa-leanpub\n" +
                "fa-sellsy\n" +
                "fa-shirtsinbulk\n" +
                "fa-simplybuilt\n" +
                "fa-skyatlas\n" +
                "fa-cart-plus\n" +
                "fa-cart-arrow-down\n" +
                "fa-diamond\n" +
                "fa-ship\n" +
                "fa-user-secret\n" +
                "fa-motorcycle\n" +
                "fa-street-view\n" +
                "fa-heartbeat\n" +
                "fa-venus\n" +
                "fa-mars\n" +
                "fa-mercury\n" +
                "fa-transgender\n" +
                "fa-transgender-alt\n" +
                "fa-venus-double\n" +
                "fa-mars-double\n" +
                "fa-venus-mars\n" +
                "fa-mars-stroke\n" +
                "fa-mars-stroke-v\n" +
                "fa-mars-stroke-h\n" +
                "fa-neuter\n" +
                "fa-genderless\n" +
                "fa-facebook-official\n" +
                "fa-pinterest-p\n" +
                "fa-whatsapp\n" +
                "fa-server\n" +
                "fa-user-plus\n" +
                "fa-user-times\n" +
                "fa-bed\n" +
                "fa-viacoin\n" +
                "fa-train\n" +
                "fa-subway\n" +
                "fa-medium\n" +
                "fa-y-combinator\n" +
                "fa-optin-monster\n" +
                "fa-opencart\n" +
                "fa-expeditedssl\n" +
                "fa-battery-full\n" +
                "fa-battery-three-quarters\n" +
                "fa-battery-half\n" +
                "fa-battery-quarter\n" +
                "fa-battery-empty\n" +
                "fa-mouse-pointer\n" +
                "fa-i-cursor\n" +
                "fa-object-group\n" +
                "fa-object-ungroup\n" +
                "fa-sticky-note\n" +
                "fa-sticky-note-o\n" +
                "fa-cc-jcb\n" +
                "fa-cc-diners-club\n" +
                "fa-clone\n" +
                "fa-balance-scale\n" +
                "fa-hourglass-o\n" +
                "fa-hourglass-start\n" +
                "fa-hourglass-half\n" +
                "fa-hourglass-end\n" +
                "fa-hourglass\n" +
                "fa-hand-rock-o\n" +
                "fa-hand-paper-o\n" +
                "fa-hand-scissors-o\n" +
                "fa-hand-lizard-o\n" +
                "fa-hand-spock-o\n" +
                "fa-hand-pointer-o\n" +
                "fa-hand-peace-o\n" +
                "fa-trademark\n" +
                "fa-registered\n" +
                "fa-creative-commons\n" +
                "fa-gg\n" +
                "fa-gg-circle\n" +
                "fa-tripadvisor\n" +
                "fa-odnoklassniki\n" +
                "fa-odnoklassniki-square\n" +
                "fa-get-pocket\n" +
                "fa-wikipedia-w\n" +
                "fa-safari\n" +
                "fa-chrome\n" +
                "fa-firefox\n" +
                "fa-opera\n" +
                "fa-internet-explorer\n" +
                "fa-television\n" +
                "fa-contao\n" +
                "fa-500px\n" +
                "fa-amazon\n" +
                "fa-calendar-plus-o\n" +
                "fa-calendar-minus-o\n" +
                "fa-calendar-times-o\n" +
                "fa-calendar-check-o\n" +
                "fa-industry\n" +
                "fa-map-pin\n" +
                "fa-map-signs\n" +
                "fa-map-o\n" +
                "fa-map\n" +
                "fa-commenting\n" +
                "fa-commenting-o\n" +
                "fa-houzz\n" +
                "fa-vimeo\n" +
                "fa-black-tie\n" +
                "fa-fonticons\n" +
                "fa-reddit-alien\n" +
                "fa-edge\n" +
                "fa-credit-card-alt\n" +
                "fa-codiepie\n" +
                "fa-modx\n" +
                "fa-fort-awesome\n" +
                "fa-usb\n" +
                "fa-product-hunt\n" +
                "fa-mixcloud\n" +
                "fa-scribd\n" +
                "fa-pause-circle\n" +
                "fa-pause-circle-o\n" +
                "fa-stop-circle\n" +
                "fa-stop-circle-o\n" +
                "fa-shopping-bag\n" +
                "fa-shopping-basket\n" +
                "fa-hashtag\n" +
                "fa-bluetooth\n" +
                "fa-bluetooth-b\n" +
                "fa-percent\n" +
                "fa-gitlab\n" +
                "fa-wpbeginner\n" +
                "fa-wpforms\n" +
                "fa-envira\n" +
                "fa-universal-access\n" +
                "fa-wheelchair-alt\n" +
                "fa-question-circle-o\n" +
                "fa-blind\n" +
                "fa-audio-description\n" +
                "fa-volume-control-phone\n" +
                "fa-braille\n" +
                "fa-assistive-listening-systems\n" +
                "fa-american-sign-language-interpreting\n" +
                "fa-deaf\n" +
                "fa-glide\n" +
                "fa-glide-g\n" +
                "fa-sign-language\n" +
                "fa-low-vision\n" +
                "fa-viadeo\n" +
                "fa-viadeo-square\n" +
                "fa-snapchat\n" +
                "fa-snapchat-ghost\n" +
                "fa-snapchat-square\n" +
                "fa-pied-piper\n" +
                "fa-first-order\n" +
                "fa-yoast\n" +
                "fa-themeisle\n" +
                "fa-google-plus-official\n" +
                "fa-font-awesome\n" +
                "fa-handshake-o\n" +
                "fa-envelope-open\n" +
                "fa-envelope-open-o\n" +
                "fa-linode\n" +
                "fa-address-book\n" +
                "fa-address-book-o\n" +
                "fa-address-card\n" +
                "fa-address-card-o\n" +
                "fa-user-circle\n" +
                "fa-user-circle-o\n" +
                "fa-user-o\n" +
                "fa-id-badge\n" +
                "fa-id-card\n" +
                "fa-id-card-o\n" +
                "fa-quora\n" +
                "fa-free-code-camp\n" +
                "fa-telegram\n" +
                "fa-thermometer-full\n" +
                "fa-thermometer-three-quarters\n" +
                "fa-thermometer-half\n" +
                "fa-thermometer-quarter\n" +
                "fa-thermometer-empty\n" +
                "fa-shower\n" +
                "fa-bath\n" +
                "fa-podcast\n" +
                "fa-window-maximize\n" +
                "fa-window-minimize\n" +
                "fa-window-restore\n" +
                "fa-window-close\n" +
                "fa-window-close-o\n" +
                "fa-bandcamp\n" +
                "fa-grav\n" +
                "fa-etsy\n" +
                "fa-imdb\n" +
                "fa-ravelry\n" +
                "fa-eercast\n" +
                "fa-microchip\n" +
                "fa-snowflake-o\n" +
                "fa-superpowers\n" +
                "fa-wpexplorer\n" +
                "fa-meetup";
        String[] splitt = eccole.split("\n");
        Arrays.stream(splitt).forEach(s -> {
            System.out.println("{label: '" + s.replace("-", " ") + "', value: 'fa " + s + "'},");

        });

    }
}
